### ISSUE TITLE
Game Play UI Wireframe

### ISSUE THREAD

**Issue by julioandryanto-1994** [GameDeveloperBatam/Run-White#17]

**Comment by idepin** [comment]
![Image](https://user-images.githubusercontent.com/58301147/188305524-1819adc1-9743-40d2-b2ef-808ea56debac.jpg)

**Comment by idepin** [comment]
Ukuran grid menyesuaikan dengan perbandingan ukuran karakter, tidak bisa dipastikan untuk skrg, perlu pair dev untuk menentukan itu

**Comment by idepin** [comment]
![Image](https://user-images.githubusercontent.com/58301147/190910952-38b028eb-137e-48e4-9ea7-d59ce242fd45.png)
