### ISSUE TITLE
Main Menu UI Wireframe

### ISSUE THREAD

**Issue by julioandryanto-1994** [GameDeveloperBatam/Run-White#2]

**Comment by idepin** [comment]
https://www.figma.com/file/ExAUYALDGtGQWnYE2BNZnI/Run-White-UI%2FUX?node-id=0%3A1

**Comment by idepin** [comment]
![Image](https://user-images.githubusercontent.com/58301147/187219143-1e5247a4-e7ad-4e75-ad0f-4d834615d83c.png)
