### ISSUE TITLE
Dungeon Gameplay Design

### ISSUE THREAD

**Issue by idepin** [GameDeveloperBatam/Run-White#23]

**Comment by kemaswara** [comment]
Need to determine the size of the grid for gameplay reasons. From today's discussions, we're shooting for 64x64 and 114x64 for the core gameplay build to get a feel of what would be good.

The size of the dungeon would significantly impact balancing and gameplay difficult, something to keep in mind. 👍

**Comment by idepin** [comment]
64 x 64 dungeon

**Comment by idepin** [comment]
Chapter #1 - The Strangers
Quest :

Eat 10 Egg and 4 Apple to Get Magic stone
Chapter #2 - Abandoned Village
Quest :

Eat 10 Egg, 5 Apple, and 2 Rat to Get information from Mr. Clown
Chapter #3 - Unexpected Journey
Quest :

Eat 10 Egg, 10 Apple, and 10 Rat to Get information from Mr. Clown
