### ISSUE TITLE
User Interface Diagram

### ISSUE THREAD

**Issue by kemaswara** [GameDeveloperBatam/Run-White#25]
The User Interface Flow

**Comment by idepin** [comment]
![Image](https://user-images.githubusercontent.com/58301147/184758289-8a5cf6bd-574e-4781-a29e-d71c968cc143.png)

**Comment by idepin** [comment]
![Image](https://user-images.githubusercontent.com/58301147/190906590-ca0a98c2-61a7-448e-bc3b-ef6791d10c9e.jpg)
