### ISSUE TITLE
Snake Eat Mechanic

### ISSUE THREAD

**Issue by julioandryanto-1994** [GameDeveloperBatam/Run-White#5]
* eat *something*
* get longer

**Comment by kemaswara** [comment]
How will the act of eating be handled?
How will we distribute the food in the map?
How will we make the snake longer?

Ideas of what needs to be answered.

**Comment by Suukii404** [comment]
- [ ] Eat System
    - [ ] Objects
        - [ ] Apple
        - [ ] Egg
        - [ ] Rat
    - [ ] Distribute Objects
    - [ ] Snake Longer
